### ISSUE TITLE
AskGPT GPT4

### ISSUE THREAD

**Issue by gaaaork** [vizovitin/foundryvtt-ask-chatgpt#6]
It seems that the option available in the GPT4 settings is not working.
I entered the API key, and in 3.5, it works perfectly fine.
However, when I switch to GPT4, I don't get any response.
Nothing happens.

**Comment by vizovitin** [comment]
In general the system will provide you with a specific error from OpenAI API.

For example, you may see the following error in case you don't have access to the GPT 4 model. Web browser console will also contain an error with a stack trace.
![error](https://github.com/vizovitin/foundryvtt-ask-chatgpt/assets/73231049/f1b70c56-5408-4db0-99d4-5eb55b2c87ca)

Note that many users don't have access to GPT 4 models yet (this includes those that are on trial or do not have a history of successful payments).

If in your case there is no error in UI or you believe the error is still on the module side, please provide the stack trace from the web browser console (F12 -> Console). Also provide your browser and Foundry versions. 
Otherwise I'm going to close this issue by the end of the week.

**Comment by vizovitin** [comment]
Requested information was not provided. Closing this.
